# **1st Dataset**

In [1]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

In [2]:
from google.colab import files
uploaded = files.upload()

Saving audit_risk.csv to audit_risk (4).csv


In [3]:
import io
audit_risk = pd.read_csv(io.BytesIO(uploaded['audit_risk.csv']))

# **Recursive feature elimination (RFE)**

In [4]:
x = audit_risk.iloc[:,0:-1] 
y = audit_risk.iloc[:,-1]

In [5]:
x = np.nan_to_num(x)
y = np.nan_to_num(y)

In [6]:
from pandas import read_csv
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

In [7]:
model = LogisticRegression(solver='lbfgs')
n_features_to_select = 10
rfe = RFE(model, n_features_to_select=n_features_to_select)
rfe.fit(x,y)

fit = rfe.fit(x, y)
print("\n\n\n")
print("Num Features: %d \n" % fit.n_features_)
print("Selected Features: \n %s" % fit.support_)
print("Feature Ranking: %s" % fit.ranking_)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression






Num Features: 10 

Selected Features: 
 [False False  True False False False False False  True False False False
  True False  True  True False  True False False False  True  True  True
 False  True]
Feature Ranking: [17  9  1  4  6  2  5  3  1 13 14 10  1  8  1  1  7  1 11 15 12  1  1  1
 16  1]


In [8]:
f = rfe.get_support(1) #the most important features
X = audit_risk[audit_risk.columns[f]] # final features`
print("Selected Column:\n ")
print(X)

Selected Column:
 
     PARA_A  TOTAL  Money_Value  Risk_D  District_Loss  RiSk_E  Score  \
0      4.18   6.68         3.38   0.676              2     0.4    2.4   
1      0.00   4.83         0.94   0.188              2     0.4    2.0   
2      0.51   0.74         0.00   0.000              2     0.4    2.0   
3      0.00  10.80        11.75   7.050              2     0.4    4.4   
4      0.00   0.08         0.00   0.000              2     0.4    2.0   
..      ...    ...          ...     ...            ...     ...    ...   
771    0.49   0.89         0.00   0.000              2     0.4    2.0   
772    0.47   0.84         0.00   0.000              2     0.4    2.0   
773    0.24   0.28         0.00   0.000              2     0.4    2.0   
774    0.20   0.20         0.00   0.000              2     0.4    2.0   
775    0.00   0.00         0.32   0.064              2     0.4    2.0   

     Inherent_Risk  CONTROL_RISK  Audit_Risk  
0            8.574           0.4      1.7148  
1         

In [9]:
import io
audit_risk = pd.read_csv(io.BytesIO(uploaded['audit_risk.csv']))

#**Univariate** **Selection**


In [10]:
Y = audit_risk.iloc[:,-1] 

X = np.nan_to_num(X)
Y = np.nan_to_num(Y)

from sklearn.feature_selection import SelectKBest,chi2
bestfeatures = SelectKBest(score_func=chi2, k=5)
select = bestfeatures.fit(X,Y)
X_train_selected = select.transform(X)

In [11]:
mask = select.get_support()
mask

array([False,  True,  True,  True, False, False, False,  True, False,
        True])

In [12]:
f = select.get_support(1) #the most important features
X = audit_risk[audit_risk.columns[f]] # final features`
print("Final Features Using Univariate: \n ")
print(X)

Final Features Using Univariate: 
 
     LOCATION_ID  PARA_A  Score_A  Risk_B  numbers
0             23    4.18      0.6   0.500      5.0
1              6    0.00      0.2   0.966      5.0
2              6    0.51      0.2   0.046      5.0
3              6    0.00      0.2   6.480      6.0
4              6    0.00      0.2   0.016      5.0
..           ...     ...      ...     ...      ...
771            9    0.49      0.2   0.080      5.0
772           16    0.47      0.2   0.074      5.0
773           14    0.24      0.2   0.008      5.0
774           18    0.20      0.2   0.000      5.0
775           15    0.00      0.2   0.000      5.0

[776 rows x 5 columns]


#**LogisticRegression**

In [13]:
from sklearn.model_selection import train_test_split

#import matplotlib.pyplot as mtp
x_train,x_test,y_train,y_test= train_test_split(X,Y,test_size=0.2, random_state=0)

In [14]:
from sklearn.preprocessing import StandardScaler
st_x= StandardScaler()
x_train= st_x.fit_transform(x_train)
x_test= st_x.fit_transform(x_test)

In [15]:
x_train = np.nan_to_num(x_train)
y_train = np.nan_to_num(y_train)

In [16]:
#x_train,x_test,y_train,y_test= train_test_split(X,y,test_size=0.3, random_state=3)
from sklearn import metrics

#x_train = np.nan_to_num(x_train)
#y_train = np.nan_to_num(y_train)
LR= LogisticRegression(random_state=0)

LR.fit(x_train,y_train)
y_pred_LR= LR.predict(x_test)

print("Report of LogisticRegression: \n")
print("Confusion Matrix: \n", metrics.confusion_matrix(y_test, y_pred_LR))
print("Accuracy: \n", metrics.accuracy_score(y_test, y_pred_LR))
print(metrics.classification_report(y_test, y_pred_LR))

Report of LogisticRegression: 

Confusion Matrix: 
 [[81 20]
 [11 44]]
Accuracy: 
 0.8012820512820513
              precision    recall  f1-score   support

           0       0.88      0.80      0.84       101
           1       0.69      0.80      0.74        55

    accuracy                           0.80       156
   macro avg       0.78      0.80      0.79       156
weighted avg       0.81      0.80      0.80       156



# **Linear Support Vector Classifier (SVC)**

In [17]:
from sklearn.svm import SVC
sv= SVC(probability=True)
sv.fit(x_train, y_train)
y_pred_sv= sv.predict(x_test)

print("Report of SVC: \n")
print("Confusion Matrix: \n", metrics.confusion_matrix(y_test, y_pred_sv))
print("Accuracy: \n", metrics.accuracy_score(y_test, y_pred_sv))
print(metrics.classification_report(y_test, y_pred_sv))

Report of SVC: 

Confusion Matrix: 
 [[93  8]
 [16 39]]
Accuracy: 
 0.8461538461538461
              precision    recall  f1-score   support

           0       0.85      0.92      0.89       101
           1       0.83      0.71      0.76        55

    accuracy                           0.85       156
   macro avg       0.84      0.81      0.83       156
weighted avg       0.84      0.85      0.84       156



# **2nd Dataset**

In [63]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

In [46]:
from google.colab import files
uploaded = files.upload()

Saving audit_risk_test.csv to audit_risk_test (6).csv


In [64]:
import io
audit_risk_test = pd.read_csv(io.BytesIO(uploaded['audit_risk_test.csv']))

# **Recursive feature elimination (RFE)**

In [69]:
a = audit_risk_test.iloc[:,0:-1] 
b = audit_risk_test.iloc[:,-1]

In [70]:
a = np.nan_to_num(a)
b = np.nan_to_num(b)

In [71]:
from pandas import read_csv
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

In [74]:
model_a = LogisticRegression(solver='lbfgs')
a_features_to_select = 10
rfe_a = RFE(model_a, n_features_to_select=a_features_to_select)
rfe_a.fit(a,b)

fit = rfe_a.fit(a,b)
print("\n\n\n")
print("Num Features: %d \n" % fit.n_features_)
print("Selected Features: \n %s" % fit.support_)
print("Feature Ranking: %s" % fit.ranking_)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression






Num Features: 10 

Selected Features: 
 [False False  True  True False  True False False  True False  True  True
  True  True False  True  True]
Feature Ranking: [8 7 1 1 6 1 2 5 1 4 1 1 1 1 3 1 1]


In [81]:
zip_a = rfe_a.get_support(1) #the most important features
A = audit_risk_test[audit_risk_test.columns[zip_a]] # final features`
print("Selected Column:\n ")
print(A)

Selected Column:
 
     PARA_A  SCORE_A  SCORE_B  Marks  MONEY_Marks  District  Loss  LOSS_SCORE  \
0      4.18        6        2      2            2         2     0           2   
1      0.00        2        2      2            2         2     0           2   
2      0.51        2        2      2            2         2     0           2   
3      0.00        2        6      6            6         2     0           2   
4      0.00        2        2      2            2         2     0           2   
..      ...      ...      ...    ...          ...       ...   ...         ...   
771    0.49        2        2      2            2         2     0           2   
772    0.47        2        2      2            2         2     0           2   
773    0.24        2        2      2            2         2     0           2   
774    0.20        2        2      2            2         2     0           2   
775    0.00        2        2      2            2         2     0           2   

     His

#**Univariate** **Selection**


In [83]:
B = audit_risk_test.iloc[:,-1] 

A = np.nan_to_num(A)
Y = np.nan_to_num(Y)

from sklearn.feature_selection import SelectKBest,chi2
bestfeatures_a = SelectKBest(score_func=chi2, k=5)
select_a = bestfeatures_a.fit(A,B)
A_train_selected = select_a.transform(A)


In [85]:
mask_a = select_a.get_support()
mask_a

array([ True,  True,  True, False,  True, False, False, False, False,
        True])

In [86]:
U = select.get_support(1) #the most important features
A = audit_risk_test[audit_risk_test.columns[U]] # final features`
print("Final Features Using Univariate: \n ")
print(A)

Final Features Using Univariate: 
 
     LOCATION_ID  PARA_A  SCORE_A  numbers  Money_Value
0             23    4.18        6      5.0         3.38
1              6    0.00        2      5.0         0.94
2              6    0.51        2      5.0         0.00
3              6    0.00        2      6.0        11.75
4              6    0.00        2      5.0         0.00
..           ...     ...      ...      ...          ...
771            9    0.49        2      5.0         0.00
772           16    0.47        2      5.0         0.00
773           14    0.24        2      5.0         0.00
774           18    0.20        2      5.0         0.00
775           15    0.00        2      5.0         0.32

[776 rows x 5 columns]


# **Linear Support Vector Classifier (SVC)**

In [87]:
a_train,a_test,b_train,b_test= train_test_split(A,B,test_size=0.3, random_state=42)

a_train = np.nan_to_num(a_train)
b_train = np.nan_to_num(b_train)

from sklearn.svm import SVC
sv_a= SVC(probability=True)
sv_a.fit(a_train, b_train)
b_pred_sv= sv_a.predict(a_test)

print("Report of SVC: \n")
print("Confusion Matrix: \n", metrics.confusion_matrix(b_test, b_pred_sv))
print("Accuracy: \n", metrics.accuracy_score(b_test, b_pred_sv))
print(metrics.classification_report(b_test, b_pred_sv))

Report of SVC: 

Confusion Matrix: 
 [[89  0]
 [60 84]]
Accuracy: 
 0.7424892703862661
              precision    recall  f1-score   support

           0       0.60      1.00      0.75        89
           1       1.00      0.58      0.74       144

    accuracy                           0.74       233
   macro avg       0.80      0.79      0.74       233
weighted avg       0.85      0.74      0.74       233



/usr/local/lib/python3.7/dist-packages/sklearn/base.py:444: UserWarning: X has feature names, but SVC was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"


#**LogisticRegression**

In [93]:
#x_train,x_test,y_train,y_test= train_test_split(X,y,test_size=0.3, random_state=3)

#x_train = np.nan_to_num(x_train)
#y_train = np.nan_to_num(y_train)
LR_a= LogisticRegression(random_state=0)

LR_a.fit(a_train,b_train)
a_pred_LR= LR_a.predict(a_test)

print("Report of LogisticRegression: \n")
print("Confusion Matrix: \n", metrics.confusion_matrix(b_test, b_pred_LR))
print("Accuracy: \n", metrics.accuracy_score(b_test, b_pred_LR))
print(metrics.classification_report(b_test, b_pred_LR))

Report of LogisticRegression: 

Confusion Matrix: 
 [[ 87   2]
 [ 30 114]]
Accuracy: 
 0.8626609442060086
              precision    recall  f1-score   support

           0       0.74      0.98      0.84        89
           1       0.98      0.79      0.88       144

    accuracy                           0.86       233
   macro avg       0.86      0.88      0.86       233
weighted avg       0.89      0.86      0.86       233



/usr/local/lib/python3.7/dist-packages/sklearn/base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
